workflows:
  simple-workflow:
    instance_type: linux
    name: Native Android
    max_build_duration: 60
    scripts:
      - name: Run tests
        script: chmod +x gradle && ./gradle test
      - name: Build debug apk
        script: ./gradle assembleDebug
    artifacts:
      - app/build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - gillvision0@gmail.com
